- shell: fc-list | grep "Source Code Pro"
  register: fclist
  ignore_errors: True

- name: Install source code pro
  import_tasks: root.yml
  become: yes
  become_method: sudo
  when: "fclist.rc != 0"
