- include_tasks: root.yml
  become: yes
  become_method: sudo

- shell: "whoami | grep root"
  ignore_errors: True
  register: isroot

- name: Dotfiles
  include_tasks: user.yml
  when: isroot.rc != 0
