- file: path={{ item }} state=directory recurse=True
  with_items:
  - ~/.config/awesome/
  - ~/.config/rofi/
  - ~/.bin/

# todo: preserve permissions
- copy:
    src={{ role_path }}/files/{{ item.src }}
    dest={{ item.dest }}
  with_items: "{{ awesome_files }}"
  when: ansible_connection == "chroot"

- synchronize:
    src={{ role_path }}/files/{{ item.src }}
    dest={{ item.dest }}
  with_items: "{{ awesome_files }}"
  when: ansible_connection != "chroot"

- git:
    repo: "https://github.com/lcpz/lain.git"
    dest: ~/.config/awesome/lain/

- git:
    repo: "https://github.com/lcpz/awesome-freedesktop"
    dest: ~/.config/awesome/freedesktop/

- git:
    repo: "https://github.com/Mic92/vicious"
    dest: ~/.config/awesome/vicious/

#- git:
#    repo: "https://github.com/streetturtle/awesome-wm-widgets.git"
#    dest: ~/.config/awesome/awesome-wm-widgets/
