- import_tasks: root.yml
  become: yes
  become_method: sudo

- import_tasks: user.yml

- shell: "whoami"
  ignore_errors: True
  register: whoami

- import_tasks: user-alex.yml
  when: "whoami.stdout == 'alex' or whoami.stdout == 'user'"
