- file: path={{ item }} state=directory recurse=True
  with_items:
  - ~/.bin/
  - ~/.config/bash/
  - ~/.config/htop/

- copy: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items: "{{ shell_files }}"
  when: ansible_connection == "chroot"

- synchronize: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items: "{{ shell_files }}"
  when: ansible_connection != "chroot"

- git:
    repo: "https://github.com/nojhan/liquidprompt.git"
    dest: ~/.config/bash/liquidprompt
