- copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
  - {src: "gitconfig", dest: "~/.gitconfig"}
  - {src: "gitignore_global", dest: "~/.gitignore_global"}
  - {src: "pastebinit.xml", dest: "~/.pastebinit.xml"}
