# ~/.bashrc: executed by bash(1) for non-login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

shopt -s checkwinsize

#
# build up
#

export VAGRANT_DEFAULT_PROVIDER=libvirt
export EDITOR=vim

source ~/.config/bash/history
source ~/.config/bash/completion
source ~/.config/bash/aliases
source ~/.config/bash/functions
source ~/.config/bash/liquidprompt/liquidprompt

PATH=$PATH:$(realpath ~)/.bin:$(realpath ~)/.local/bin

#
# custom
#

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

dscomplete=/usr/local/lib/python2.7/dist-packages/dsjk-0.0.1-py2.7.egg/ds/autocomplete/bash
[ -f $dscomplete ] && source $dscomplete

export CARP_DIR=~/projects/Carp/
