- name: Install system-wide packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - net-tools
    - tcpdump
    - traceroute
    - iputils-ping
    - icedove
    - liferea
    - transmission-gtk
    - mpv
    - vlc
    - cmus
    - xnview
    - apvlv
    - djview4
    - qpdfview
    - qpdfview-djvu-plugin
    - calcurse
    - keepassx
    - pastebinit
    - usbutils
    - firmware-misc-nonfree
    - wicd-curses
    - wicd-cli
    - wicd-gtk
    # - python3-multibootusb
