- shell: "whoami | grep root"
  ignore_errors: True
  register: isroot

- shell: cat /etc/hostname
  register: hostname

- import_tasks: root.yml
  become: yes
  become_method: sudo

- import_tasks: root-nowshahr.yml
  become: yes
  become_method: sudo
  when: hostname.stdout_lines[0] == 'nowshahr'

- import_tasks: root-vepar.yml
  become: yes
  become_method: sudo
  when: hostname.stdout_lines[0] == 'vepar'

- import_tasks: user.yml
  when: isroot.rc != 0

- import_tasks: user-nowshahr.yml
  when: isroot.rc != 0 and hostname.stdout_lines[0] == 'nowshahr'

- import_tasks: user-vepar.yml
  when: isroot.rc != 0 and hostname.stdout_lines[0] == 'vepar'
