- apt: name={{ item }} state=present
  with_items:
    - lightdm
    - thunar
    - neofetch
    - arandr

- apt: name={{ item }} state=present
  with_items:
    - pciutils
    - pulseaudio
    - pasystray
    - paman
    - pavucontrol
    - pavumeter

- file: path=/usr/share/images/ state=directory
- copy: src=hi-there.jpg dest=/usr/share/images/hi-there.jpg
- copy: src=lightdm-gtk-greeter.conf dest=/etc/lightdm/

- shell: cat /etc/hostname
  register: hostname

- apt: name=tumbler state=absent autoremove=yes
  when: "hostname.stdout_lines[0] != 'nowshahr'"

- command: locale-gen
