- name: Check is emacs installed
  shell: command -v emacs >/dev/null 2>&1
  register: is_emacs_exists
  ignore_errors: yes

- name: Install
  become: yes
  become_method: sudo
  include_tasks: root.yml
  when: is_emacs_exists.rc != 0

- shell: "whoami | grep root"
  ignore_errors: True
  register: isroot

- name: Dotfiles
  include_tasks: user.yml
  when: root_install_emacs || isroot.rc != 0
