# - file: path=~/.emacs.d/ state=absent

- git:
    repo: "https://github.com/syl20bnr/spacemacs"
    dest: ~/.emacs.d
    version: v0.200.13
#    version: v0.200.12

- file: path=~/.emacs.d/ state=directory recurse=True
- copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=preserve
  with_items:
  - {src: .emacs.d, dest: ~/}
  - {src: .spacemacs, dest: ~/}
