- name: Check is nvim installed
  shell: command -v nvim >/dev/null 2>&1
  register: is_nvim_exists
  ignore_errors: yes

- apt_repository:
    repo: deb http://httpredir.debian.org/debian stretch-backports main contrib non-free
    state: present

- name: neovim
  block:
    - name: Install vim
      apt: name={{ item }} state=present default_release=stretch-backports
      with_items:
        - git
        - neovim
        - python-pip
        - python3-pip
        - silversearcher-ag
    - shell: pip install "neovim>=0.2.6" && pip3 install "neovim>=0.2.6"
    - shell: update-alternatives --set vim /usr/bin/nvim
    - shell: pip install "{{ item }}"
      with_items:
          - "flake8"
          - "pylint"
  when: is_nvim_exists.rc != 0
  become: yes
  become_method: sudo

- name: Check is fzf installed
  shell: command -v fzf >/dev/null 2>&1
  register: is_fzf_exists
  ignore_errors: yes

- name: fzf
  block:
    - stat: path=/usr/local/bin/fzf
      register: fzf
    - unarchive:
        src: https://github.com/junegunn/fzf-bin/releases/download/0.17.4/fzf-0.17.4-linux_amd64.tgz
        dest: /usr/local/bin/
        remote_src: yes
      when: not fzf.stat.exists
  when: is_fzf_exists.rc != 0
  become: yes
  become_method: sudo
