- file: path=~/.config/nvim/ state=directory recurse=True
- file: path=~/.config/nvim/autoload/ state=directory recurse=True

- copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=preserve
  with_items: "{{ vim_files }}"

- stat: path=~/.config/nvim/autoload/plug.vim
  register: plug

- get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: ~/.config/nvim/autoload/plug.vim
  when: not plug.stat.exists

- shell: vim +PlugInstall +qall

# - stat: path=~/.config/nvim/bundle/Vundle.vim
#   register: vundle
#
# - git:
#     repo: "https://github.com/VundleVim/Vundle.vim.git"
#     dest: ~/.config/nvim/bundle/Vundle.vim
#   when: not vundle.stat.exists
#
# - shell: vim +PluginInstall +qall

# - shell: find ~/.vim/bundle/ -type d -name ".git" -exec rm -r "{}" \;
#   ignore_errors: True
#   when: purge_vundle_git
