files:
  - {src: "bash/", dest: "~/.config/bash/"}
  - {src: "bashrc", dest: "~/.bashrc"}
  - {src: "bash_profile", dest: "~/.bash_profile"}
  - {src: "liquidpromptrc", dest: "~/.liquidpromptrc"}
  - {src: "psqlrc", dest: "~/.psqlrc"}
  - {src: "curlrc", dest: "~/.curlrc"}
  - {src: "wgetrc", dest: "~/.wgetrc"}
  - {src: "inputrc", dest: "~/.inputrc"}
  - {src: "htoprc", dest: "~/.config/htop/htoprc"}
