- name: Check is mosh installed
  shell: command -v mosh >/dev/null 2>&1
  register: is_mosh_exist
  ignore_errors: yes

- import_tasks: root.yml
  become: yes
  become_method: sudo
  when: is_mosh_exist.rc != 0

- import_tasks: user.yml
