- name: Reboot the server
  command: /sbin/reboot
  when: file.stat.exists == true

- name: Wait for reboot
  local_action: wait_for host={{ inventory_hostname }} state=started
  when: file.stat.exists == true

- name: Reboot the server
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0

- pause: seconds=30

- local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }}
  register: result
  until: result.rc == 0
  retries: 30
  delay: 10

- name: Rebooted
  shell: uptime
