- name: Update packages
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
  register: output

- name: Display changes
  debug: "{{ output.stdout_lines }}"

- name: Create log directory
  file: path="{{ log_dir }}" state=directory

- name: Write changes to logfile
  copy:
    content: "{{ output.stdout }}"
    dest: "{{ log_dir }}/dist-upgrade_{{ ansible_date_time.iso8601 }}.log"
