- name: Install essential packages
  apt: name={{ item }} state=present
  with_items:
  - git
  - g++
  - libgtk-3-dev
  - gtk-doc-tools
  - gnutls-bin
  - valac
  - intltool
  - libpcre2-dev
  - libgnutls28-dev
  - libgirepository1.0-dev
  - libxml2-utils
  - gperf

- name: Clone termite repository
  git:
    repo: "https://github.com/thestinger/termite.git"
    dest: /var/tmp/termite

- name: Clone vte-ng repository
  git:
    repo: "https://github.com/thestinger/vte-ng.git"
    dest: /var/tmp/vte-ng

- name: Build and install vte-ng
  shell: export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"; \
         cd /var/tmp/vte-ng && \
         ./autogen.sh && \
         make && \
         make install

- name: Build and install termite
  shell: export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"; \
         cd /var/tmp/termite && \
         make && \
         make install

- name: Set termite as default shell
  shell: ldconfig && \
         mkdir -p /lib/terminfo/x && \
         ln -s \
             /usr/local/share/terminfo/x/xterm-termite \
             /lib/terminfo/x/xterm-termite && \
         update-alternatives --install \
             /usr/bin/x-terminal-emulator \
             x-terminal-emulator \
             /usr/local/bin/termite \
             100

- name: Cleanup
  file: path={{ item }} state=absent
  with_items:
  - /var/tmp/termite
  - /var/tmp/vte-ng
