- file: path=~/.config/termite/ state=directory recurse=True

- copy: src=themes/ dest=~/.config/termite/
- file:
    src: ~/.config/termite/{{ termite_theme }}
    dest: ~/.config/termite/config
    state: link
    force: yes
