- hosts: all
  vars:
    purge_vundle_git: True
    root_install_nvim: True
  roles:
    # - role: debian-upgrade
    #   tags: [maintenance]

    - role: debian-docker
      tags: [setup, maintenance]

    - role: debian-deploy-user
      tags: [setup, users]

    - role: dotfiles-ssh
      tags: [console, ssh]

    - role: dotfiles-shell
      tags: [console, shell]

    - role: dotfiles-tmux
      tags: [console, tmux]

    - role: dotfiles-ranger
      tags: [console, ranger]

    - role: dotfiles-vim
      tags: [console, vim]
