- hosts: all
  vars:
  - purge_vundle_git: True
  roles:
    - role: dotfiles-ssh
      tags: [console, ssh]

    - role: dotfiles-shell
      tags: [console, shell]

    - role: dotfiles-tmux
      tags: [console, tmux]

    - role: dotfiles-ranger
      tags: [console, ranger]

    - role: dotfiles-vim
      tags: [console, vim]
